{% set name = "tacco" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tacco-{{ version }}.tar.gz
  sha256: 9ea3d87ffbbc91ce67b8929f54895c57f080a391ab9bfccc1d3e626314abeab6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools <=60
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.7
    - requests
    - joblib
    - numba >=0.51.2
    - numpy
    - matplotlib-base !=3.7
    - seaborn
    - sparse_dot_mkl >=0.7.3
    - scanpy >=1.7.0
    - statsmodels
    - anndata
    - pandas >=1.1.0
    - scipy >=1.6.0
    - mkl
    - mkl-service
    - scikit-learn
    - threadpoolctl
    - pyamg

test:
  imports:
    - tacco
  source_files:
    - tests/
  commands:
    - pytest -k "not test_benchmark_annotate"
  requires:
    - pytest

about:
  home: https://github.com/simonwm/tacco
  summary: 'TACCO: Transfer of Annotations to Cells and their COmbinations'
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENCE.txt
    - NOTICE.md
  doc_url: https://simonwm.github.io/tacco
  dev_url: https://github.com/simonwm/tacco

extra:
  recipe-maintainers:
    - simonwm
    - JWatter
